### ISSUE TITLE
Activated resource layer doesn't show up in overlays in map widget or search

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#383] opened 2019-10-18 22:23 UTC

**Comment by robgaston** [comment] 2019-11-18 18:12
@whatisgalen I believe this is just because layers don't show up if there are no instances added for a given geojson node, which is by design.  I'm going to close this for now, but feel free to reopen if I am missing something here

**Closed as completed by robgaston** 2019-11-18 18:12 UTC
