### ISSUE TITLE
Can Create New Resource link be moved to top of Add new Relationship fields?

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#681] opened 2021-07-29 12:05 UTC
**Issue Description:** (priority 2 enhancement) - Add New Relationship fields across all models – can we have the create a new resource option at the top of the Add New Relationship fields? 
1.	 There looks to be an issue with scrolling through lots of Records to get to create a new Digital Object.
2.	Is there a way that The Create ‘button’ is fixed in place so that it is always there, or on top?

![image](https://user-images.githubusercontent.com/78143228/127488743-d01a50db-cdaa-45d1-90c8-fa03ebd34bd9.png)

**Comment by chrisdolby-HE** [comment] 2022-04-01 15:08
This is not essential, but would be much more useful than being at the bottom of the list, as we have many thousands of instances of multiple resource types, and it's not clear that the option even exists unless you've typed yourself free of any partially matching resources (no matches).

**Comment by chiatt** [comment] 2022-04-01 17:08
@chrisdolby-HE & @rlwilliamss, I understand why this feels inconvenient, but it is actually by design the 'Create' option is at the bottom and unavailable without a search. The reason is that it prevents users from creating resource instances until they have first confirmed that the one they are about to create is not in the system. This helps prevent duplicate resources from getting created. Duplicate resource instances can be very problematic if resource relationships are unknowingly created using duplicates. It could be extremely challenging to disentangle them. 

We don't want change this behavior in core for this reason, but if the risk of creating duplicates is low in HER, we could override the resource instance widget in HER and move the 'Create' option to the top.

**Comment by StucakeGLHER** [comment] 2022-04-01 20:37
@chiatt I think the risk is low, so if you could move the 'Create' option to the top, that would be good. Thanks

**Comment by aj-he** [comment] 2022-05-10 09:52
@StucakeGLHER @chrisdolby-HE  I am in agreement with @chiatt that this behaviour should stay out of Arches. Putting it separately into Arches-HER will bring with it technical debt that the other HERs would have no choice but to pick up if they adopt Arches-HER.

I would prefer that we leave the default behaviour in both Arches and Arches-HER, see how the users get on and then add it specifically to Keystone later if it is a problem. I will close this ticket if you are in agreement?

**Comment by aj-he** [comment] 2022-11-16 11:59
Closed as not reported as an issue since go live

**Closed as completed by aj-he** 2022-11-16 11:59 UTC
