### ISSUE TITLE
Update vertical nav to show icons (like base Arches) in Consultations

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#182] opened 2019-09-04 18:11 UTC

**Comment by dwuthrich** [comment] 2019-09-04 19:21
When collapsed, the nav bar should show the icons associated with each task so that users can navigate no matter the nav bar state.  The nav bar should work just like Arches base vertical nav bar

**Comment by chiatt** [comment] 2019-09-05 19:27
duplicate of #184

**Closed as completed by chiatt** 2019-09-05 19:27 UTC
