### ISSUE TITLE
Consultations vertical menu is broken

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#337] opened 2019-10-02 03:45 UTC
See: ![Screen Shot 2019-10-01 at 8.44.20 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/7fddb78f-5b8e-4d3d-a8b8-0dcc1137b80f)

**Comment by chiatt** [comment] 2019-10-02 16:48
Duplicate of #338

**Closed as completed by chiatt** 2019-10-02 16:48 UTC
Labels: Priority: High
