### ISSUE TITLE
Consultation Type card overlapping with white space/radio buttons

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#659] opened 2021-06-09 09:04 UTC
**Describe the issue** - When filling out and saving the Consultation Type card, a white line with what appears to be a radio button is displayed over the card in the card tree.

**Steps to reproduce**
1) Open https://esriarches.fargeo.com/arches-her/resource/2cf195f8-805b-4f97-9133-cbd94bf5a01f

3) Click on the Consultation Type card and fill out the fields

4) Save the card:

![image](https://user-images.githubusercontent.com/78143228/121326038-112dc400-c90a-11eb-8d43-f9278d9c3d35.png)

**Comment by chiatt** [comment] 2021-06-09 12:54
Duplicate of #547

**Closed as completed by chiatt** 2021-06-09 12:54 UTC
